title: Word Clock One
description: Documentation for the Word Clock One smart clock!
remote_theme: pmarsceill/just-the-docs

url: https://skyextechnologies.github.io

heading_anchors: false

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: purple