name: Build and Publish ESPHome Firmware and Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish-word-clock-one:
    name: Publish Word Clock One
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: word-clock-one.yaml
      name: Word Clock One
      manifest_filename: word-clock-one-manifest.json
      clean: false
      esphome_version: latest